//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildBuddy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBuildEntities1 : DbContext
    {
        public PCBuildEntities1()
            : base("name=PCBuildEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinets { get; set; }
        public virtual DbSet<CoolingSystem> CoolingSystems { get; set; }
        public virtual DbSet<GraphicCard> GraphicCards { get; set; }
        public virtual DbSet<Memory> Memories { get; set; }
        public virtual DbSet<Motherboard> Motherboards { get; set; }
        public virtual DbSet<PowerSupply> PowerSupplies { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
    }
}
