//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompareList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URLName { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    }
}
