//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildBuddy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int id { get; set; }

        [Required(ErrorMessage = "The first name field is required.")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Enter Valid First Name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "The last name field is required.")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Enter Valid Last Name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "The email field is required.")]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "Enter Valid Email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "The phone number field is required.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Enter Valid Phone number of 10 digits.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "The message field is required.")]
        [StringLength(500, ErrorMessage = "Message should be less than 500 characters.")]
        public string Message { get; set; }
    }
}
