//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        public int id { get; set; }
        public string company { get; set; }
        public string model_name { get; set; }
        public string price { get; set; }
        public string socket { get; set; }
        public string form_factor { get; set; }
        public string max_memory { get; set; }
        public string memory_slots { get; set; }
        public string supported_memory_type { get; set; }
        public string interface_field { get; set; }
        public string wattage { get; set; }
        public string description { get; set; }
        public string imagelink { get; set; }
    }
}
