//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedBuild
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Motherboard { get; set; }
        public string Processor { get; set; }
        public string Memory { get; set; }
        public string Storage { get; set; }
        public string GraphicsCard { get; set; }
        public string CoolingSystem { get; set; }
        public string PowerSupply { get; set; }
        public string Cabinet { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> TotalWattage { get; set; }
    }
}
